repos:
  - repo: https://github.com/shenxianpeng/hadolint-pre-commit
    rev: v2.14.0.1
    hooks:
      - id: hadolint
        name: hadolint
        files: (^|/)Dockerfile(?:\..*)?$
        args:
          - --ignore=DL3008
