services:
  cavestory:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ghcr.io/nayetdet/cavestory-nx-docker:latest
    ports:
      - "3000:3000"
    volumes:
      - cavestory-data:/config

volumes:
  cavestory-data:
